title: Vegan & Cheese
email: ""
description: >-
  Delicious vegan recipes made easy. Fast meals, homemade sauces, and meatless comfort foods from the comfort of a home kitchen.
url: "https://veganandcheese.com"   
baseurl: ""
instagram_username: veganandcheese

permalink: /:title/
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Optional: Display future-dated posts
future: true

# =====================================
# Pages Collection for _pages directory
# =====================================

collections:
  pages:
    output: true
    permalink: /:name/
  recipes:
    output: true
    permalink: /recipes/:name/


defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: recipe
