title: Vegan & Cheese
email: ""
description: >-
  Delicious vegan recipes made easy. Fast meals, homemade sauces, and meatless comfort foods from the comfort of a home kitchen.
baseurl: "/FoodBlog" # Leave blank unless deploying to a subpath
url: "https://kevikell-y.github.io" # Replace with your GitHub username or custom domain
instagram_username: veganandcheese
permalink: /:title/
theme: minima
plugins:
  - jekyll-feed

# Optional: Display future-dated posts
future: true

# =====================================
# Pages Collection for _pages directory
# =====================================
collections:
  pages:
    output: true
    permalink: /:name/

